#import "../../../public/utils.typ": blog-post, caution, todo

#show: blog-post.with(
  "The future I was promised cannot exist",
  draft: true,
  tilslut: (),
)

// if youre someone reading this on github, this is my ramblings and i will release it once im ready

LLMs are net positive for programming, and net negative for humanity.

#caution(title: "Disclaimer")[
  the only time llms were involved in the process of writing was during the proofreading phase, just before I send to human proofreaders. the only words written by llms are grammatical corrections. kagi proofread works a shitload better than ltex-ls-plus, and let's not even talk about fucking grammarly or some other proprietary shit which is worse than ltex-ls
]

programming is in a unique position.

programming, now, is only done digitally, there's no physical aspect to it . in the years past, the act of programming involved  #todo[wikipedia link for "punch cards"], then, afaiu with #todo[wikipedia link for ed], the scroll back part of the terminal was printed in the physical sense. on a paper, in the real world, where you can touch the "programming".

An external observer might think that writing the code IS programming. However, programming IS NOT the act of typing out code.

in the past decade, the biggest (not the best) innovation in the software world are llms. there's very few things which can even come close to it. so why is it that the general sentiment towards them is negative. in fact it's so negative that the sentiment has been slowly spreading towards other things like ai in general, the fucking word algorithm, and data centers???

llms are a net positive for developers, not entirely positive mind you, but def net positive. you need experience to know exactly what you want to prompt to get the best out of ai, and I'm def not there, nor do I care to be there.

llms are a tool, and just like all tools, you need to learn when to use it, and when not to not .

I practically vibe coded via github copilot before it was a thing.

I wrote comments in a python script, and let the llm write the functions for me. For the core of my program, I didn't trust it, and copied code from stack overflow. my main "contribution" was guiding the llm into writing the functions.

in the main function I wrote some trash code to tie together functions and even then more than half of it was written by copilot. and this was in the days of chatgpt 3.

the script never left my ssd. it didn't even get backed up to my laptop and phone, I didn't have either of them back then.

this is how I understand llms. I think llms, for programming, come under the category of a more advanced lsp + auto complete. It "understands" the code like #todo[[tree sitter]], and completes the text like the primitive algorithm in... let's say.... #todo[Kate]. It sees partially written text, scans the document for words which start with same letters, and then suggests you the completed word. And when I say "understands" I don't mean that in the sense that it knows your requirements, I mean that in the sense that it understands the grammar. it knows what functions look like, what variable declaration looks like. another thing, while Kate uses the words in the document as it's database of words, llms have an internal database which has the most common ways to solve the problems. similar to Kate, it can suggest invalid statements, you can't tab your way to completion, you need to check if it's valid and is doing what you expect.

it's not inventing new things.

#todo[Find the video]

in a recent video [[tsoding]] proposes that people encode their knowledge as code, but only a minority of the people read the code. llms on the other hand were trained on the code and thus the knowledge is stored in them. they don't invent new things, they're just retrieving the knowledge that people encoded in their code but no one bothered to read.

I think of it as an advanced form of copy pasting

and thus, i also think that the code generated by the llm, is the responsibility of the human.

I think it's fine to use llms for things which will never be released under a license, or if it can be scruitinized under a patent, which really limits when you can use llms and the CEOs hate that.

however once it comes to licensing the code written by llms, its impossible. some of the code is MIT, which I understand to means you can use it however, where ever, doesn't matter. but, inadvertantly, some of the code will be gpl 3,which is a viral copyleft license which requires you to release the code under the same, or a compatible license.

does that mean all llm generated code should be under the strictest copy left license? no.

see, I don't trust these companies to only train the llms with publically available code. I expect that Microsoft allowed (at least) openai to train on private repositories.

so avoid openai models and you should be fine right? nope

I don't have any proof for it, or any idea how it could happen. but I have a hunch that the models are also trained on proprietary code and data.

and if I were the owner or cto of a company, i would just avoid getting into legal trouble with it.

maybe some of the proofreaders will know about some court case or whatever, I know meta is under one for training on non public domain books. tho, what else do you expect from Facebook

so what can they be used for? I'm not sure to be quite honest.

until there's a open source llm, and not just open weight, which has a public dataset, which only contains public domain data, maybe MIT, maybe Apache licensed data, and all the code used to train the llms, it's just too risky to use in production.

imo, until we can reproduce the same blob on our own, using community shared hardware, its not open source

but those llms will be trash until the ability to extract knowledge from the limited dataset improves.

now then, let's talk about the potential future which could have an open source llm, who's weights I got from, idfk, some fucking research group in china.

---

windows recall is universally considered bad

but i think it was the most useful thing microsoft released in the recent years

same with the fucking ai friend pin

consider this:

how many times have you had the thought "i wish i had a search option for my brain"

that's windows recall and ai friend pin

computers are waaay better at calculations and remembering things compared to humans,

so deligating the bulk of that task to computer seems reasonable

you could ask the computer about some task like "where did i keep my notebook with drawing of mina ha"

and the computer would tell you where it is.

this is an issue which can be solved by selfdicipline and being organized... but shit happens

ok, thats the good part, yeah? but the security implications are massive

the computer knows your each and every move. its not enough that theres a microphone and camera in our pockets,
but the computer doesn't understand what it's seeing or hearing for the most part

you can confuse the stt by just having an accent it wasnt trained on.

but now, with llms and genai, the computer will also understand what the footage is, and what youre talking about.

not only will it know what it is, it will understand what youre doing, or the true meaning behind your words for most common phrases.

well, shit

let's use local llms then!

...the data is still stored on your pc and easily recoverable unless you encrypt it

---

next thing,

llms and genai in general wouldve been such a boon for disabled people

i love having an option on bluesky which forces me to add alt text for photos and videos, but im gonna be honest, i hate writing them

i have alt text on 100% of my images and videos, but the quality of them is attrocious to the point im unsure if theyre helful.

llms on the other hand would've been able to infer what im yapping about in the preceeding paragraph and knew about what the most important part of the image is,
why im adding an image in the first place.

the best alt text ive written is here
https://bsky.app/profile/did:plc:rwi65xn77uzhgyewkfbuuziz/post/3mebhaxrzoc2j

it says what the image is at a highlevel, explains what the image is about, and then finally, the least important part theres the ocr

compare that to any of the cat pics which is basically just some variation of cat

there's also been so many times i just dont have the energy to write alt text and end up not posting the image

i wouldnt trust the alt text from llm, but its 90% of the way there and it makes it easier that way.

but thats not where the priority of the corporations is.

their priority is cost cutting at all stages and whereever possible

they want to remove the artists by using genai to create images

anytime i see ai image, i puke a bit on inside and no matter how interested i was, i just go away

as soon as i see them, i dont trust anything

so far the only case ive thought they might be useful is for programmer art,
and even then id rather see someone's horrible scribbles on paper where i have no idea whats happening

so, id rather the image be useless than see ai generated image

not to mention the amount of scams people are doing with the images, and falsifying evidence.

i hate how bitter and sckeptical ive become due to exposure to the world and now llms and genai

well then, audio rant next

stt has pretty good for a while now atleast for me

whisper was really good even if it halucinated during silence, it even understood my weirdass accent

thats all fine and well ig

but then, the other side, tts is a horrible idea

again, scams, and evidence falsification

the only positive i can think of is autodubbing and making npcs in games talk.

but in both cases, it would be the last possible option

youtube has autodubbing and its horrible, i DO NOT want to see content dubbed from another language

its horrible

as for npcs, i havent seen it in use yet, so, unsure how i feel about it

also, when i say npcs, i dont mean it in old general "non player character" way, i mean it in the new faceless nameless characters, with no anchor to the game.
characters who would not have anything and only exist as a statistic.

like villagers in minecraft

but in the end itll be just one small touch to add to the game, i would understand if people prefer their npcs to not talk





